data = fetch("http://127.0.0.1:5000/getNews/YOUR-SEARCH-TERM-HERE")
    .then(res => res.json())
    .then(data => {for(let i = 0; i < data.processedData.length; i++)
        console.log(`\n Image: ${data.processedData[i].Image}\n Headline: ${data.processedData[i].Headline}\n Link: ${data.processedData[i].Link}`)
    })
